### ISSUE TITLE
Could not get this to work on a @Configuration class

### ISSUE THREAD

**Issue by bjornharvold** [lc-nyovchev/lombok-spring-qualifier#1]
Is it required that the class be annotated with @Service?

**Comment by bjornharvold** [comment]
```
@Configuration
@RequiredArgsConstructor
public class MyConfig {
  @Qualifier('specificMongoClient')
  private final MongoClient mongoClient;
}
```

This will insert any mongoClient it can find. In my case, the incorrect one. I had to revert to @Autowired to get it to work.

**Comment by lc-nyovchev** [comment]
interesting, I haven't tried it with @Configuration, just normal @Repository @Service @Controller, etc.
Did you put the:
`lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier`
in your lombok.config file?

**Comment by lc-nyovchev** [comment]
I guess you can always use normal Java to see what Lombok generated for you. In my case, I can see that the constructor that Lombok generated has all the annotated elements that I need. Something like this:

`
public static void main(String[] args) {
		assertHasNumberOfAnnotatedParameters(LombokInjectorWithQualifiersConfig.class, 4);
		assertIsQualifierAnnotationForArgument(LombokInjectorWithQualifiersConfig.class, 0, DESTINATION_ONE);
		assertIsQualifierAnnotationForArgument(LombokInjectorWithQualifiersConfig.class, 1, DESTINATION_TWO);
		assertIsQualifierAnnotationForArgument(LombokInjectorWithQualifiersConfig.class, 2, DESTINATION_THREE);
		assertIsQualifierAnnotationForArgument(LombokInjectorWithQualifiersConfig.class, 3, DESTINATION_FOUR);
	}

	private static void assertHasNumberOfAnnotatedParameters(Class<?> clazz, int expectedNumberOfAnnotatedParams) {
		Constructor<?>[] declaredConstructors = clazz.getDeclaredConstructors();
		Constructor<?> declaredConstructor = declaredConstructors[0];
		assertEquals(1, declaredConstructors.length);
		Annotation[][] parameterAnnotations = declaredConstructor.getParameterAnnotations();
		assertEquals(expectedNumberOfAnnotatedParams, parameterAnnotations.length);
	}

	private static void assertIsQualifierAnnotationForArgument(Class<?> clazz, int argumentNr, String desiredValue) {
		Constructor<?>[] declaredConstructors = clazz.getDeclaredConstructors();
		Constructor<?> declaredConstructor = declaredConstructors[0];
		assertEquals(1, declaredConstructors.length );
		Annotation[][] parameterAnnotations = declaredConstructor.getParameterAnnotations();
		assertEquals(1, parameterAnnotations[argumentNr].length);
		Annotation annotation = parameterAnnotations[argumentNr][0];
		assertEquals(Qualifier.class, annotation.annotationType());
		assertEquals(desiredValue, ((Qualifier) annotation).value());
	}
`

**Comment by lc-nyovchev** [comment]
What was the issue @bjornharvold, out of curiosity?

**Comment by bjornharvold** [comment]
Injecting two different MongoClient beans
